#include "AreaStrings.h"

/* Main */
const QString AreaString::organizationName = "Epitech Innovative Project";
const QString AreaString::organizationDomain = "eip.epitech.eu";
const QString AreaString::applicationName = "AreaQuest Server";

/* Server Initialization */
const QString AreaString::settingsFile = "Settings.ini";
const QString AreaString::settingsFileNotFound = "AreaQuest Settings: File Not Found !";
const QString AreaString::initMessage = "AreaQuest Server Initializing...";
const QString AreaString::logFile = "./AreaQuestServerLog.log";
const QString AreaString::portValue = "Network/Port";
const QString AreaString::launchSuccessMessage = "AreaQuest Server Launched at: %1";
const QString AreaString::launchFailureMessage = "AreaQuest Server Launching: Failed !";

/* Database Initialization */
const QString AreaString::initDatabaseMessage = "AreaQuest Database Initializing...";
const QString AreaString::dbName = "areaquest";
const QString AreaString::dbNameProram = "AreaQuestDB";
const QString AreaString::dbAddressValue ="Database/Address";
const QString AreaString::launchDatabaseSuccessMessage = "AreaQuest Database Connection Status: Success !";
const QString AreaString::launchDatabaseFailureMessage = "AreaQuest Database Connection Status: Failure !";
const QString AreaString::dbMySQLValue = "Database/MySQL";
const QString AreaString::dbMySQLDriver = "QMYSQL";
const QString AreaString::dbMySQLMessage = "Communication with MySQL Database ....";
const QString AreaString::dbMySQLAdminName = "DBAdmin";
const QString AreaString::dbMySQLAdminPassword = "areaquest";
const QString AreaString::dbMySQLOption = "MYSQL_OPT_RECONNECT=1";
const QString AreaString::dbPSQLValue = "Database/PostgreSQL";
const QString AreaString::dbPSQLDriver = "QPSQL";
const QString AreaString::dbPSQLMessage = "Communication with PostgreSQL Database ....";
const QString AreaString::dbPSQLAdminName = "areaquest";
const QString AreaString::dbPSQLAdminPassword = "areaquest";

/* Clients Connections */
const QString AreaString::connectedMessage = "Connected\n";
const QString AreaString::clientInfoMessage = "[%1] Client Connected on IP address: <%2> !";
const QString AreaString::disconnectedMessage = "[%1] <%2> Disconnected from Server !";
const QString AreaString::dateFormat = "dd/MM/yyyy - hh:mm:ss";
const QString AreaString::dateTimeFormat = "hh:mm:ss";
const QString AreaString::clientCommand = "[%1] <%2> %3";
const QString AreaString::endl = "\n";
const QString AreaString::space = " ";
const QString AreaString::blank = "";

/* Clients Commands */
const QString AreaString::createAccountCommand = "CREATE_ACCOUNT";
const QString AreaString::loginAccountCommand = "LOGIN_ACCOUNT";
const QString AreaString::invalidCommand = "INVALID_COMMAND\n";
const QString AreaString::getCharCommand = "GET_CHARACTER_INFO";
const QString AreaString::updateCharCommand = "UPDATE_CHARACTER_INFO";
const QString AreaString::updatePosCommand = "UPDATE_POSITION";
const QString AreaString::exploreAroundCommand = "EXPLORE_AROUND";
const QString AreaString::battleRequestCommand = "BATTLE_REQUEST";
const QString AreaString::battleRequestAcceptCommand = "BATTLE_REQUEST_ACCEPT";
const QString AreaString::battleRequestDenyCommand = "BATTLE_REQUEST_DENY";
const QString AreaString::battleTurnFinishCommand = "BATTLE_TURN_FINISH";
const QString AreaString::battleTurnStartCommand = "BATTLE_TURN_START";
const QString AreaString::battleGiveUpCommand = "BATTLE_GIVEUP";
const QString AreaString::sendMessageCommand = "SEND_MESSAGE";
const QString AreaString::receiveMessageCommand = "RECEIVE_MESSAGE ";
const QString AreaString::battleTurnWaitCommand = "BATTLE_TURN_WAIT ";
const QString AreaString::getRankingTopCommand = "GET_RANKING_TOP";
const QString AreaString::getRankingMeCommand = "GET_RANKING_ME";

/* State Messages */
const QString AreaString::registerAccountMessage = "<***> Attempting to Register a New Account...";
const QString AreaString::loginAccountMessage = "<***> Attempting to login to an account...";
const QString AreaString::createEmailInfoFailureMessage = "<***> Registering Account %1: Failed (Email already existing).";
const QString AreaString::createNicknameInfoFailureMessage = "<***> Registering Account %1: Failed (Nickname already existing).";
const QString AreaString::loginAccountPasswordInfoFailureMessage = "<***> Authentication Account %1: Failed (Wrong Password).";
const QString AreaString::loginAccountEmailInfoFailureMessage = "<***> Authentication Account %1: Failed (Unregistered Account).";
const QString AreaString::loginAccountInfoSuccessMessage = "<***> Authentication Account %1: Success !";
const QString AreaString::playerOnlineInfoMessage = "<***> Player %1: Connected !";
const QString AreaString::playerOfflineInfoMessage = "<***> Player %1: Disconnected !";
const QString AreaString::playerOnlineInfoFailureMessage = "<***> Set Online Status for %1: Failed !";
const QString AreaString::playerOfflineInfoFailureMessage = "<***> Set Offline Status for %1: Failed !";
const QString AreaString::registerAccountInfoSuccessMessage = "<***> Registering Account for %1 on ID Account: %2";
const QString AreaString::registerAccountInfoFailureMessage = "<***> Registering Account for %1: Failed !";
const QString AreaString::createBankInfoSuccessMessage = "<***> Creating Bank Holder for %1 on ID Account: %2";
const QString AreaString::createBankInfoFailureMessage = "<***> Creating Bank Holder for %1: Failed !";
const QString AreaString::createInventoryInfoSuccessMessage = "<***> Creating Inventory Holder for %1 on ID Account: %2";
const QString AreaString::createInventoryInfoFailureMessage = "<***> Creating Inventory Holder for %1: Failed !";
const QString AreaString::createEquipmentInfoSuccessMessage = "<***> Creating Equipment Holder for %1 on ID Account: %2";
const QString AreaString::createEquipmentInfoFailureMessage = "<***> Creating Equipment Holder for %1: Failed !";
const QString AreaString::createPositionInfoSuccessMessage = "<***> Creating Position Holder for %1 on ID Account: %2";
const QString AreaString::createPositionInfoFailureMessage = "<***> Creating Position Holder for %1: Failed !";
const QString AreaString::createStatsInfoSuccessMessage = "<***> Creating Stats Holder for %1 on ID Account: %2";
const QString AreaString::createStatsInfoFailureMessage = "<***> Creating Stats Holder for %1: Failed !";
const QString AreaString::createCharacterInfoSuccessMessage = "<***> Create Character %1 for Account %2: Success !";
const QString AreaString::createCharacterInfoFailureMessage = "<***> Create Character %1 for Account %2: Failed !";
const QString AreaString::checkExistingFailureMessage = "<***> Check Existing Accounts: Failure !";
const QString AreaString::checkAuthFailureMessage = "<***> Check Authentification Account: Failure !";
const QString AreaString::sendSuccessInfoMessage = "<***> %1 Send Message to: %2";
const QString AreaString::updatePositionInfoSuccessMessage = "<***> Update Position for Player %1";
const QString AreaString::exploreAroundInfoSuccessMessage = "<***> Sent Player List around %1";
const QString AreaString::getCharacterInfoSuccessMessage = "<***> Sent Character Info for Player %1";
const QString AreaString::updateCharacterInfoSuccessMessage = "<***> Update Character Info for Player %1";
const QString AreaString::battleResultInfoMessage = "<***> Battle Finished - Victory: %1 Defeat: %2";
const QString AreaString::battleRequestInfoMessage = "<***> Player %1 Send Battle Request for Player %2";
const QString AreaString::battleStartInfoMessage = "<***> Player %1 Versus Player %2 Battle Start !";
const QString AreaString::battleDeniedInfoMessage = "<***> Player %1 Versus Player %2 Request: Denied";
const QString AreaString::battleInterruptedInfoMessage = "<***> Battle Interrupted - Victory: %1 Defeat: %2";

/* Returned Values to Clients */
const QString AreaString::registerAccountFailureMessage = "CREATE_ACCOUNT_FAILURE\n";
const QString AreaString::registerAccountSuccessMessage = "CREATE_ACCOUNT_SUCCESS\n";
const QString AreaString::createEmailFailureMessage = "CREATE_EMAIL_FAILURE\n";
const QString AreaString::createNicknameFailureMessage = "CREATE_NICKNAME_FAILURE\n";
const QString AreaString::loginAccountEmailFailureMessage = "LOGIN_EMAIL_FAILURE\n";
const QString AreaString::loginAccountPasswordFailureMessage = "LOGIN_ACCOUNT_FAILURE\n";
const QString AreaString::loginAccountSuccessMessage = "LOGIN_ACCOUNT_SUCCESS %1\n";
const QString AreaString::sendNotConnectedFailureMessage = "SEND_MESSAGE_PLAYER_NOT_CONNECTED\n";
const QString AreaString::sendNotJsonFailureMessage = "SEND_MESSAGE_INCORRECT_JSON\n";
const QString AreaString::sendSuccessMessage = "SEND_MESSAGE_SUCCESS\n";
const QString AreaString::updatePositionSuccessMessage = "UPDATE_POSITION SUCCESS\n";
const QString AreaString::updatePositionFailureMessage = "UPDATE_POSITION FAILURE\n";
const QString AreaString::updatePositionParamFailureMessage = "UPDATE_POSITION INCORRECT_PARAMS\n";
const QString AreaString::exploreAroundParamFailureMessage = "EXPLORE_AROUND INCORRECT_PARAMS\n";
const QString AreaString::getCharacterInfoParamFailureMessage = "GET_CHARACTER_INFO INCORRECT_PARAMS\n";
const QString AreaString::getCharacterInfoFailureMessage = "GET_CHARACTER_INFO_FAILURE\n";
const QString AreaString::updateCharacterSuccessMessage = "UPDATE_CHARACTER_INFO_SUCCESS\n";
const QString AreaString::updateCharacterFailureMessage = "UPDATE_CHARACTER_INFO_FAILURE\n";
const QString AreaString::updateCharacterParamFailureMessage = "UPDATE_CHARACTER_INFO INCORRECT_PARAMS\n";
const QString AreaString::battleDecisionLossMessage = "BATTLE_DECISION_LOSS\n";
const QString AreaString::battleDecisionWinMessage = "BATTLE_DECISION_WIN\n";
const QString AreaString::battleFailureMessage = "BATTLE_COMMAND_FAILURE\n";
const QString AreaString::battleRequestFailureMessage = "BATTLE_REQUEST_FAILED\n";
const QString AreaString::battleRequestAcceptFailureMessage = "BATTLE_REQUEST_ACCEPT_FAILURE\n";
const QString AreaString::battleRequestDeniedMessage = "BATTLE_REQUEST_DENIED\n";
const QString AreaString::battleRequestDenyFailureMessage = "BATTLE_REQUEST_DENY_FAILURE\n";
const QString AreaString::getRankingMeFailureMessage = "GET_RANKING_ME_FAILURE\n";
const QString AreaString::getRankingTopFailureMessage = "GET_RANKING_TOP_FAILURE\n";

/* Database Queries */
const QString AreaString::getNicknameQuery = "SELECT visible_nickname FROM account";
const QString AreaString::getEmailNicknameQuery = "SELECT email, visible_nickname FROM account";
const QString AreaString::getEmailPasswordNicknameQuery = "SELECT email, password, visible_nickname FROM account";
const QString AreaString::registerAccountQuery = "INSERT INTO account (email, password, visible_nickname, account_creation, status) VALUES (:email, :password, :nickname, NOW(), 0)";
const QString AreaString::createBankQuery = "INSERT INTO bank (idBank) VALUES (default)";
const QString AreaString::createInventoryQuery = "INSERT INTO inventory (idInventory) VALUES (default)";
const QString AreaString::createEquipmentQuery = "INSERT INTO equipment (idEquipment) VALUES (default)";
const QString AreaString::createPositionQuery = "INSERT INTO characterposition (idCharacterPosition) VALUES (default)";
const QString AreaString::createStatsQuery = "INSERT INTO characterstats (idCharacterStats) VALUES (default)";
const QString AreaString::createCharacterInfoQuery = "INSERT INTO characterinfo (Account_idAccount, Bank_idBank, Inventory_idInventory, Equipment_idEquipment, CharacterPosition_idCharacterPosition, CharacterStats_idCharacterStats) VALUES (:idAccount, :idBank, :idInventory, :idEquipment, :idCharacterPosition, :idCharacterStats)";
const QString AreaString::setOnlineStatusQuery = "UPDATE account SET status = 1 WHERE visible_nickname = :nickname";
const QString AreaString::setOfflineStatusQuery = "UPDATE account SET status = 0, last_connection = NOW() WHERE visible_nickname = :nickname";
const QString AreaString::updatePositionQuery = "UPDATE characterposition SET latitude = :latitude, longitude = :longitude WHERE idCharacterPosition = (SELECT CharacterPosition_idCharacterPosition FROM characterinfo WHERE Account_idAccount = (SELECT idAccount FROM account WHERE visible_nickname = :nickname))";
const QString AreaString::exploreAroundQuery = "SELECT account.visible_nickname, characterinfo.class, characterinfo.lvl, characterposition.latitude, characterposition.longitude, get_distance_metres((SELECT characterposition.latitude FROM characterinfo INNER JOIN characterposition ON characterinfo.CharacterPosition_idCharacterPosition = characterposition.idCharacterPosition WHERE characterinfo.Account_idAccount = (SELECT idAccount FROM account WHERE visible_nickname = :nickname)), (SELECT characterposition.longitude FROM characterinfo INNER JOIN characterposition ON characterinfo.CharacterPosition_idCharacterPosition = characterposition.idCharacterPosition WHERE characterinfo.Account_idAccount = (SELECT idAccount FROM account WHERE visible_nickname = :nickname)), characterposition.latitude, characterposition.longitude) AS distance FROM characterinfo INNER JOIN characterposition ON characterinfo.CharacterPosition_idCharacterPosition = characterposition.idCharacterPosition INNER JOIN account ON characterinfo.Account_idAccount = account.idAccount WHERE account.visible_nickname != :nickname AND account.status = 1 HAVING distance BETWEEN 0 AND 20000 ORDER BY distance ASC LIMIT 20";
const QString AreaString::getCharacterInfoQuery = "SELECT characterinfo.class, characterinfo.lvl, characterinfo.experience, characterinfo.next_lvl, bank.money, characterstats.hp, characterstats.hp_max, characterstats.mp, characterstats.mp_max, characterstats.attack, characterstats.defense, characterstats.ability_power, characterstats.magic_resist, characterstats.agility, equipment.headgear_idItem, equipment.armor_idItem, equipment.legs_idItem, equipment.shoes_idItem, equipment.righthand_idItem, equipment.lefthand_idItem FROM characterinfo INNER JOIN bank ON characterinfo.Bank_idBank = bank.idBank INNER JOIN characterstats ON characterinfo.CharacterStats_idCharacterStats = characterstats.idCharacterStats INNER JOIN equipment ON characterinfo.Equipment_idEquipment = equipment.idEquipment WHERE characterinfo.Account_idAccount = (SELECT idAccount FROM account WHERE visible_nickname = :nickname)";
const QString AreaString::getItemListQuery = "SELECT inventoryitemlist.Item_idItem AS idItem, inventoryitemlist.quantity FROM inventoryitemlist WHERE Inventory_idInventory = (SELECT Inventory_idInventory FROM characterinfo WHERE Account_idAccount = (SELECT idAccount FROM account WHERE visible_nickname = :nickname))";
const QString AreaString::getIdCharacterInfoQuery = "SELECT idCharacter, Bank_idBank, Inventory_idInventory, Equipment_idEquipment, CharacterStats_idCharacterStats FROM characterinfo WHERE Account_idAccount = (SELECT idAccount FROM account WHERE visible_nickname = :nickname)";
const QString AreaString::updateCharacterInfoQuery = "UPDATE characterinfo, bank, equipment, characterstats SET characterinfo.class = :class, characterinfo.experience = :experience, characterinfo.lvl = :level, characterinfo.next_lvl = :next_level, bank.money = :money, equipment.headgear_idItem = :idHeadgear, equipment.armor_idItem = :idArmor, equipment.legs_idItem = :idLegs, equipment.shoes_idItem = :idShoes, equipment.righthand_idItem = :idRighthand, equipment.lefthand_idItem = :idLefthand, characterstats.hp = :hp, characterstats.mp = :mp, characterstats.hp_max = :hp_max, characterstats.mp_max = :mp_max, characterstats.attack = :attack, characterstats.defense = :defense, characterstats.ability_power = :ability_power, characterstats.magic_resist = :magic_resist, characterstats.agility = :agility WHERE idCharacter = :idCharacter AND idBank = :idBank AND idEquipment = :idEquipment AND idCharacterStats = :idStats";
const QString AreaString::addItemListQuery = "INSERT INTO inventoryitemlist (inventoryitemlist.Inventory_idInventory, inventoryitemlist.Item_idItem, inventoryitemlist.quantity) VALUES (:idInventory, :idItem, :quantity)";
const QString AreaString::deleteItemListQuery = "DELETE FROM inventoryitemlist WHERE Inventory_idInventory = :idInventory";
const QString AreaString::getPlayerStatsQuery = "SELECT characterinfo.class, characterinfo.lvl, characterstats.hp, characterstats.hp_max, characterstats.mp, characterstats.mp_max, characterstats.attack, characterstats.defense, characterstats.ability_power, characterstats.magic_resist, characterstats.agility FROM characterinfo INNER JOIN characterstats ON characterinfo.CharacterStats_idCharacterStats = characterstats.idCharacterStats WHERE Account_idAccount = (SELECT idAccount FROM account WHERE visible_nickname = :nickname)";
const QString AreaString::getPlayerInfoQuery = "SELECT characterinfo.class, characterinfo.lvl FROM characterinfo WHERE Account_idAccount = (SELECT idAccount FROM account WHERE visible_nickname = :nickname)";
const QString AreaString::getRankingTopQuery = "SELECT visible_nickname, class, lvl FROM account INNER JOIN characterinfo ON account.idAccount = characterinfo.Account_idAccount ORDER BY characterinfo.lvl DESC LIMIT 100";
const QString AreaString::getRankingMeQuery = "SELECT visible_nickname, class, lvl FROM account INNER JOIN characterinfo ON account.idAccount = characterinfo.Account_idAccount ORDER BY characterinfo.lvl DESC";

/* Bind Values */
const QString AreaString::emailBindValue = ":email";
const QString AreaString::passwordBindValue = ":password";
const QString AreaString::nicknameBindValue = ":nickname";
const QString AreaString::idAccountBindValue = ":idAccount";
const QString AreaString::idBankBindValue = ":idBank";
const QString AreaString::idInventoryBindValue = ":idInventory";
const QString AreaString::idEquipmentBindValue = ":idEquipment";
const QString AreaString::idPositionBindValue = ":idCharacterPosition";
const QString AreaString::idStatsBindValue = ":idCharacterStats";
const QString AreaString::latitudeBindValue = ":latitude";
const QString AreaString::longitudeBindValue = ":longitude";
const QString AreaString::idCharacterBindValue = ":idCharacter";
const QString AreaString::idCharacterStatsBindValue = ":idStats";
const QString AreaString::idClassBindValue = ":class";
const QString AreaString::idExperienceBindValue = ":experience";
const QString AreaString::idLevelBindValue = ":level";
const QString AreaString::idMoneyBindValue = ":money";
const QString AreaString::idNextLevelBindValue = ":next_level";
const QString AreaString::idHeadgearBindValue = ":idHeadgear";
const QString AreaString::idArmorBindValue = ":idArmor";
const QString AreaString::idLegsBindValue = ":idLegs";
const QString AreaString::idShoesBindValue = ":idShoes";
const QString AreaString::idRighthandBindValue = ":idRighthand";
const QString AreaString::idLefthandBindValue = ":idLefthand";
const QString AreaString::hpBindValue = ":hp";
const QString AreaString::mpBindValue = ":mp";
const QString AreaString::hpMaxBindValue = ":hp_max";
const QString AreaString::mpMaxBindValue = ":mp_max";
const QString AreaString::attackBindValue = ":attack";
const QString AreaString::defenseBindValue = ":defense";
const QString AreaString::abilityPowerBindValue = ":ability_power";
const QString AreaString::magicResistBindValue = ":magic_resist";
const QString AreaString::agilityBindValue = ":agility";
const QString AreaString::idItemBindValue = ":idItem";
const QString AreaString::quantityBindValue = ":quantity";

/* JSON Name Values */
const QString AreaString::nicknameJsonValue = "nickname";
const QString AreaString::messageJsonValue = "message";
const QString AreaString::classJsonValue = "class";
const QString AreaString::levelJsonValue = "level";
const QString AreaString::latitudeJsonValue = "latitude";
const QString AreaString::longitudeJsonValue = "longitude";
const QString AreaString::distanceJsonValue = "distance";
const QString AreaString::visibleNicknameJsonValue = "visible_nickname";
const QString AreaString::lvlJsonValue = "lvl";
const QString AreaString::experienceJsonValue = "experience";
const QString AreaString::nextLevelJsonValue = "next_level";
const QString AreaString::nextLvlJsonValue = "next_lvl";
const QString AreaString::moneyJsonValue = "money";
const QString AreaString::hpJsonValue = "hp";
const QString AreaString::hpMaxJsonValue = "hp_max";
const QString AreaString::mpJsonValue = "mp";
const QString AreaString::mpMaxJsonValue = "mp_max";
const QString AreaString::attackJsonValue = "attack";
const QString AreaString::defenseJsonValue = "defense";
const QString AreaString::abilityPowerJsonValue = "ability_power";
const QString AreaString::magicResistJsonValue = "magic_resist";
const QString AreaString::agilityJsonValue = "agility";
const QString AreaString::idHeadgearJsonValue = "idHeadgear";
const QString AreaString::idArmorJsonValue = "idArmor";
const QString AreaString::idLegsJsonValue = "idLegs";
const QString AreaString::idShoesJsonValue = "idShoes";
const QString AreaString::idRighthandJsonValue = "idRighthand";
const QString AreaString::idLefthandJsonValue = "idLefthand";
const QString AreaString::headgearIdItemJsonValue = "headgear_idItem";
const QString AreaString::armorIdItemJsonValue = "armor_idItem";
const QString AreaString::legsIdItemJsonValue = "legs_idItem";
const QString AreaString::shoesIdItemJsonValue = "shoes_idItem";
const QString AreaString::righthandIdItemJsonValue = "righthand_idItem";
const QString AreaString::lefthandIdItemJsonValue = "lefthand_idItem";
const QString AreaString::statsJsonValue = "stats";
const QString AreaString::equipmentJsonValue = "equipment";
const QString AreaString::inventoryJsonValue = "inventory";
const QString AreaString::idCharacterJsonValue = "idCharacter";
const QString AreaString::idBankJsonValue = "Bank_idBank";
const QString AreaString::idInventoryJsonValue = "Inventory_idInventory";
const QString AreaString::idEquipmentJsonValue = "Equipment_idEquipment";
const QString AreaString::idCharacterStatsJsonValue = "CharacterStats_idCharacterStats";
const QString AreaString::idItemJsonValue = "idItem";
const QString AreaString::quantityJsonValue = "quantity";
const QString AreaString::attackNameJsonValue = "attack_name";
const QString AreaString::damageJsonValue = "damage";
const QString AreaString::playersJsonValue = "players";
const QString AreaString::positionJsonValue = "position";
